############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Sobre Nosotros"
url = "about/"
weight = 2

[[main]]
name = "Productos"
url = "products/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4


[[main]]
name = "Contacto"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Sobre Nosotros"
url = "about/"
weight = 2

[[footer]]
name = "Productos"
url = "products/"
weight = 3

# [[footer]]
# name = "Service"
# url = "service/"
# weight = 4

# [[footer]]
# name = "Pricing"
# url = "pricing/"
# weight = 5

# [[footer]]
# name = "FAQ"
# url = "faq/"
# weight = 6

[[footer]]
name = "Contacto"
url = "contact/"
weight = 7